# GitHub Action для создания календаря

# имя проекта
name: Current year calendar


# Управляет запуском действия. Это действие выполняется каждые 6 часов.
on:
  schedule:
    - cron: "0 */6 * * *"

# Эта команда позволяет нам автоматически запускать действие с вкладки «Действия».
  workflow_dispatch:

# Последовательность прогонов в этом рабочем процессе:
jobs:
  # Этот рабочий процесс содержит одно задание под названием «сборка» - "build"
  build:
    # Тип бегуна, на котором будет выполняться задание
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания.
    steps:

    # Проверяет репозиторий в $GITHUB_WORKSHOP, чтобы ваша работа могла получить к нему доступ
      - uses: lowlighter/metrics@latest

      with:
        filename: metrics.plugin.calendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_calendar: yes

          - name: Full history calendar
            uses: lowlighter/metrics@latest
            with:
              filename: metrics.plugin.calendar.full.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_calendar: yes
              plugin_calendar_limit: 0
