# GitHub Action for generating a contribution graph with a snake eating your contributions.
# GitHub Action для создания графика вкладов со змеей, пожирающей ваши взносы.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
# Управляет запуском действия. Это действие выполняется каждые 6 часов.
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
# Эта команда позволяет нам автоматически запускать действие с вкладки «Действия».
  workflow_dispatch:

# The sequence of runs in this workflow:
# Последовательность прогонов в этом рабочем процессе:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
#      - uses: actions/checkout@v2
      - uses: Platane/snk@aebc3a92857730857d5a96010a3538f16bbec662  # v3.0.0

    # Generates the snake
      - uses: Platane/snk@aebc3a92857730857d5a96010a3538f16bbec662  # v3.0.0
        id: snake-gif
        with:
          github_user_name: BEPb
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}